/**
 * Credits for the chapter backgrounds.
 *
 * Generated by `scripts/build-chapter-art.mjs`; do not hand-edit. These are
 * other people's photographs under Creative Commons, and attribution is a
 * condition of those licences rather than a courtesy, so the credits are a
 * module the About page imports, which means a photograph cannot reach the site
 * without one.
 */

export interface ChapterArt {
  /** Category slug: the join to `public/bg/<slug>.webp`. */
  slug: string;
  title: string;
  artist: string;
  license: string;
  sourceUrl: string;
}

export const chapterArt: readonly ChapterArt[] = [
  {
    slug: "pregnancy-antenatal",
    title: "Autumn baby to be (Unsplash)",
    artist: "Arteida MjESHTRI arteidamjeshtri",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Autumn_baby_to_be_(Unsplash).jpg"
  },
  {
    slug: "labour-birth",
    title: "A HUSBAND HOLDS HIS WIFE'S HAND DURING DELIVERY OF THEIR BABY IN LORETTO HOSPITAL IN NEW ULM, MINNESOTA. THERE ARE... - NARA - 558167",
    artist: "Phillips, Kathy, Photographer (NARA record: 8467756)",
    license: "Public domain",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_HUSBAND_HOLDS_HIS_WIFE%27S_HAND_DURING_DELIVERY_OF_THEIR_BABY_IN_LORETTO_HOSPITAL_IN_NEW_ULM,_MINNESOTA._THERE_ARE..._-_NARA_-_558167.jpg"
  },
  {
    slug: "newborn-care",
    title: "Newborn baby sleeps in a basket",
    artist: "Elizabeth",
    license: "CC0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Newborn_baby_sleeps_in_a_basket.jpg"
  },
  {
    slug: "feeding-nutrition",
    title: "Breastfeeding a newborn baby, Moscow, Russia",
    artist: "Vyacheslav Argenberg",
    license: "CC BY 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:Breastfeeding_a_newborn_baby,_Moscow,_Russia.jpg"
  },
  {
    slug: "complications",
    title: "MODULAR NICU WITH HEPAFILTERS",
    artist: "Kaveri appala",
    license: "CC BY-SA 4.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:MODULAR_NICU_WITH_HEPAFILTERS.jpg"
  },
  {
    slug: "postnatal-quality",
    title: "A Syrian refugee and her newborn baby at a clinic in Ramtha, Jordan (9613483141)",
    artist: "DFID - UK Department for International Development",
    license: "CC BY 2.0",
    sourceUrl: "https://commons.wikimedia.org/wiki/File:A_Syrian_refugee_and_her_newborn_baby_at_a_clinic_in_Ramtha,_Jordan_(9613483141).jpg"
  }
];

export function artFor(slug: string): ChapterArt | undefined {
  return chapterArt.find((art) => art.slug === slug);
}
